improved configure: more narrow raw search,  use pkg-config info as first source

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,56 +1,83 @@
 #!/bin/sh
 
 findLuaInclude() {
-    VERSION=$1
-    PATH=$2
-    FILE=`/usr/bin/find $PATH -name luaconf.h | /usr/bin/grep $VERSION`
-    if [ x$FILE != 'x' ]; then
-        PATH=`/usr/bin/dirname $FILE`
-        echo $PATH
-    fi
+	VERSION=$1
+	PATH=$2
+	FILE=`/usr/bin/find $PATH -name luaconf.h | /usr/bin/grep $VERSION`
+	if [ x$FILE != 'x' ]; then
+		PATH=`/usr/bin/dirname $FILE`
+		echo $PATH
+	fi
 }
 
 findLuaLib() {
-    VERSION=$1
-    PATH=$2
-    FILE=`/usr/bin/find $PATH -name "liblua$VERSION.so"`
-    if [ x$FILE != 'x' ]; then
-        PATH=`/usr/bin/dirname $FILE`
-        echo $PATH
-    fi
+	VERSION=$1
+	PATH=$2
+	FILE=`/usr/bin/find $PATH -name "liblua$VERSION.so"`
+	if [ x$FILE != 'x' ]; then
+		PATH=`/usr/bin/dirname $FILE`
+		echo $PATH
+	fi
 }
 
 findLuaBin() {
-    VERSION=$1
-    PATH=$2
-    PATH=`/usr/bin/find $PATH -type f -name "lua$VERSION"`
-    if [ x$PATH != 'x' ]; then
-        echo $PATH
-    fi
+	VERSION=$1
+	PATH=$2
+	PATH=`/usr/bin/find $PATH -type f -name "lua$VERSION"`
+	if [ x$PATH != 'x' ]; then
+		echo $PATH
+	fi
 }
 
 writeLuaInclude() {
-    VERSION=$1
-    INCPATH=$2
-    LIBPATH=$3
-    BINPATH=$4
-    echo "LUAVER   := $VERSION" > Lua.inc
-    echo "LUAINC   := $INCPATH" >> Lua.inc
-    echo "LUALIBDIR:= $LIBPATH" >> Lua.inc
-    echo "LUABIN   := $BINPATH" >> Lua.inc
+	VERSION=$1
+	INCPATH=$2
+	LIBPATH=$3
+	BINPATH=$4
+	echo "LUAVER   := $VERSION" > Lua.inc
+	echo "LUAINC   := $INCPATH" >> Lua.inc
+	echo "LUALIBDIR:= $LIBPATH" >> Lua.inc
+	echo "LUABIN   := $BINPATH" >> Lua.inc
+	echo "LUALIBS  := -llua$VERSION -L$LIBPATH" >> Lua.inc
 }
 
-SEARCHPATH=/usr
-for VERSION in 5.4 5.3 5.2; do
-    INCPATH=`findLuaInclude $VERSION $SEARCHPATH`
-    LIBPATH=`findLuaLib $VERSION $SEARCHPATH`
-    BINPATH=`findLuaBin $VERSION $SEARCHPATH`
-    if [ x$INCPATH != 'x' ] && [ x$LIBPATH != 'x' ]; then
-        writeLuaInclude $VERSION $INCPATH $LIBPATH $BINPATH
-        exit 0
-    fi
+for VERSION in 5.4 5.3 5.2 ; do
+	>&2 echo "Checking for version $VERSION ..."
+	LUAVERSION=`/usr/bin/pkg-config --variable=version lua$VERSION`
+	if [ x$LUAVERSION != 'x' ]; then
+		INCPATH="`/usr/bin/pkg-config --variable=includedir lua$VERSION`/lua$VERSION"
+		LIBPATH=`/usr/bin/pkg-config --variable=libdir lua$VERSION`
+		PREFIX=`/usr/bin/pkg-config --variable=prefix lua$VERSION`
+		if [ x$INCPATH != 'x' ] && [ x$LIBPATH != 'x' ] && [ x$PREFIX != 'x' ] ; then
+			BINPATH="$PREFIX/bin"
+			writeLuaInclude $VERSION $INCPATH $LIBPATH $BINPATH
+			>&2 echo "/usr/bin/pkg-config --variable=includedir lua$VERSION => $INCPATH"
+			>&2 echo "/usr/bin/pkg-config --variable=libdir lua$VERSION => $LIBPATH"
+			>&2 echo "/usr/bin/pkg-config --variable=prefix lua$VERSION => $PREFIX, BINPATH=$PREFIX/bin"
+			>&2 echo "/usr/bin/pkg-config --variable=version lua$VERSION => $LUAVERSION"
+			>&2 echo "Wrote file Lua.inc"
+			exit 0
+		fi
+	fi
 done
 
-echo "Lua installation (version 5.2,5.3 or 5.4) not found!"
+>&2 echo "Failed to determine Lua package info with pkg-config, now searching with raw find ..."
+for VERSION in 5.4 5.3 5.2; do
+	>&2 echo "Checking for version $VERSION ..."
+	INCPATH=`findLuaInclude $VERSION "/usr/local/include /usr/include"`
+	LIBPATH=`findLuaLib $VERSION "/usr/local/lib /usr/lib"`
+	BINPATH=`findLuaBin $VERSION "/usr/bin /usr/local/bin"`
+	if [ x$INCPATH != 'x' ] && [ x$LIBPATH != 'x' ]; then
+		writeLuaInclude $VERSION $INCPATH $LIBPATH $BINPATH
+		>&2 echo "Lua include path = $INCPATH"
+		>&2 echo "Lua library path = $LIBPATH"
+		>&2 echo "Lua binary path = $BINPATH"
+		>&2 echo "Lua version = $VERSION"
+		>&2 echo "Wrote file Lua.inc"
+		exit 0
+	fi
+done
+
+>&2 echo "Lua installation (version 5.2,5.3 or 5.4) not found!"
 exit 1
 
